# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my_postgres_data: